apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: app-example
  name: app-example
  namespace: app-example-ns
spec:
  clusterIP: 172.30.19.135
  ports:
  - name: web
    port: 8080
  selector:
    name: app-example
