---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-example
  namespace: app-example-ns
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - app-example
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
