apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: example-app-sub
  namespace: app-example-ns
  labels:
    app: app-example
  annotations:
    apps.open-cluster-management.io/git-path: application
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: app-example-ns/example-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: example-app-pr
