---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: example-app-latest
  namespace: app-example-ns
spec:
  type: GitHub
  pathname: https://github.com/minageorge83/mina-playland.git
